include: package:flutter_lints/flutter.yaml

linter: 
  rules: 
    always_declare_return_types: true
    depend_on_referenced_packages: false
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_final_locals: true
    require_trailing_commas: false

analyzer:
  plugins:
    - dart_code_metrics

  exclude:
    - lib/**/**/*.freezed.dart
    - lib/**/**/**/**/*.freezed.dart
    - lib/**/**/*.g.dart
    - lib/**/**/**/**/*.g.dart
    - lib/**/**/*.gr.dart
    - lib/**/**/**/**/*.gr.dart
    - lib/generated_plugin_registrant.dart
    - copan/lib/**/*.doc_widget.dart

  errors:
    missing_return: error
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    no_logic_in_create_state: ignore
    deprecated_member_use_from_same_package: ignore

dart_code_metrics:
  metrics:
    maximum-nesting-level: 5
    source-lines-of-code: 60
  metrics-exclude:
    - test/**
  rules:
    - binary-expression-operand-order
    - double-literal-format
    - no-boolean-literal-compare
    - no-equal-then-else
    - always-remove-listener
    - avoid-non-null-assertion
    - avoid-unused-parameters
    - prefer-trailing-comma
    - avoid-wrapping-in-padding