name: cloudwalk_test_mobile_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  auto_route: ^7.8.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  http: ^1.1.0
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  flutter_gen_runner: ^5.3.2
  json_serializable: ^6.7.0

flutter_gen:
  output: lib/common/generated/
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700